name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "newsnow-db"
database_name = "newsnow-db"
database_id = "8abb7672-855a-43a6-a12a-4da11ae2ceba"
